# Generated by Django 4.2.5 on 2023-12-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image_url',
            new_name='post_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
